import type { Metadata } from 'next'
import { LegalPage, H2, P, UL } from '../legal/legal'

export const metadata: Metadata = { title: 'Terms of Service — Prov' }

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 2026">
      <P>These Terms govern your use of the Prov platform (the &ldquo;Service&rdquo;) operated by [Company Legal Name]. By creating an account you agree to these Terms.</P>

      <H2>The Service</H2>
      <P>Prov helps agencies and creators discover influencers, match sponsors, send outreach from their own connected email, manage deals, and generate contracts and reports. Features and pricing may change over time.</P>

      <H2>Subscriptions & billing</H2>
      <UL>
        <li>Paid access is billed through Stripe at the price shown at checkout ($299/month unless otherwise stated).</li>
        <li>Free trials convert to paid unless cancelled before the trial ends.</li>
        <li>You can cancel anytime via the billing portal; access continues until the end of the paid period. Fees already paid are non-refundable except where required by law.</li>
      </UL>

      <H2>Acceptable use — outreach & anti-spam</H2>
      <P>You are solely responsible for the messages you send through the Service and for complying with all applicable laws, including the CAN-SPAM Act, GDPR/ePrivacy, CASL, and similar regulations. You agree to:</P>
      <UL>
        <li>Only contact recipients where you have a lawful basis to do so.</li>
        <li>Include accurate sender information and a working way to opt out, and honor opt-out requests promptly.</li>
        <li>Not send unlawful, deceptive, harassing, or bulk unsolicited email that violates your email provider&apos;s policies.</li>
      </UL>
      <P>You send outreach from your own connected email account and are subject to that provider&apos;s sending limits and terms. We may suspend accounts that abuse the Service or generate spam complaints.</P>

      <H2>Your content & data</H2>
      <P>You retain ownership of your campaigns, branding, and contacts. You grant us a limited license to process this content solely to provide the Service. You are responsible for the accuracy and lawful use of any creator or contact data you import or generate.</P>

      <H2>Contracts generated by the Service</H2>
      <P>Contract templates and AI-generated documents are provided for convenience and are not legal advice. Review them with a qualified professional before relying on them.</P>

      <H2>Disclaimers & liability</H2>
      <P>The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum extent permitted by law, [Company Legal Name] is not liable for indirect, incidental, or consequential damages, and our total liability is limited to the amount you paid in the 12 months preceding the claim.</P>

      <H2>Termination</H2>
      <P>You may stop using the Service at any time. We may suspend or terminate access for violation of these Terms or misuse of the Service.</P>

      <H2>Changes</H2>
      <P>We may update these Terms; material changes will be communicated. Continued use after changes means you accept them.</P>

      <H2>Contact</H2>
      <P>[Company Legal Name], [contact@yourdomain.com], [Mailing Address].</P>
    </LegalPage>
  )
}
